spring:
  application:
    name: dnd

  datasource:
    url: jdbc:postgresql://192.168.0.10:5432/bdd
    username: bdd_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect