spring:
  application:
    name: dnd

  datasource:
    url: jdbc:postgresql://192.168.13.13:5432/dnd
    username: dnd_user
    password: "*ccpml183*"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect